# Generated by Django 5.2.5 on 2025-08-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=100)),
                ('hosting_type', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('bandwidth', models.CharField(max_length=50)),
                ('api_available', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
