# Generated by Django 5.2.5 on 2025-08-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingplan',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
