# Generated by Django 5.2.5 on 2025-08-28 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_hostingplan_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingPlanSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hosting_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='plans.hostingplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
