# Generated by Django 5.2.5 on 2025-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_hostingplansnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hostingplansnapshot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
