# Generated by Django 5.2.5 on 2025-09-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_hostingplan_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingplan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hostingplansnapshot',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
