# Generated by Django 5.2.5 on 2025-09-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_hostingplan_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingplan',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hostingplansnapshot',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
