# Generated by Django 5.2.5 on 2025-09-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_hostingplan_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingplansnapshot',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
