# Generated by Django 5.2.5 on 2025-09-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_alter_hostingplansnapshot_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingplansnapshot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
