# Generated by Django 5.2.5 on 2025-09-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_hostingplansnapshot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingplansnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
