# Generated by Django 5.2.5 on 2025-09-01 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_alter_hostingplansnapshot_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingplansnapshot',
            name='description',
        ),
        migrations.AlterField(
            model_name='hostingplansnapshot',
            name='hosting_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.hostingplan'),
        ),
    ]
